### PR TITLE
Gray background color to company card inside article

### PR DESCRIPTION
**Pull request by inoyakaigor**
URL: https://habr.com/ru/company/skillfactory/blog/680868/

Image: 
Было:
image
Стало:
image

### CODE REVIEW

**Comment by valsaven** [comment]
Thank you! Please, rename the commit in English (similar to other commits)

**Comment by inoyakaigor** [comment]
@valsaven Commit message or these PR name?

**Comment by valsaven** [comment]
@inoyakaigor Both, if you don't mind. Imagine how hard it is to watch other projects where someone creates issues and PRs in Japanese or Chinese =)

**Comment by inoyakaigor** [comment]
@valsaven Changed name of PR, but the Github does not allow to change commit message in web UI so it still in Russian

**Comment by valsaven** [comment]
You can rebase, change the name of the commit, and force-push it. I think it will work.
Or, if it's easier for you, I can close this PR and you open a new one.

**Comment by inoyakaigor** [comment]
@valsaven done

**Comment by valsaven** [comment]
Thank you!

**Pull request merged**
